### ISSUE TITLE
New plot idea

### ISSUE THREAD

**Issue by matlipson** [isithot/isithotrightnow#4]
Perhaps we could create a plot recording the last 30 days of averages. I'm thinking a series of squares in a heatmap type plot, red for HOT down to blue for COLD.

**Comment by rensa** [comment]
I think it's worth us thinking carefully about how we present new plots, if we decide to make them. There are a lot of different variations we could do on what we have, and I'm reticent to throw them all on the page.

Which isn't to say that this plot is a bad idea! But I'd like it if we could sit down (either IRL or here) and think about the main questions we want to ask, then think about the best plots to use to answer each one.
