### ISSUE TITLE
Distribution plot

### ISSUE THREAD

**Issue by matlipson** [isithot/isithotrightnow#5]
We should work on the description to make it clearer (people are still confused). Consider changing  temperature axis match with the timeseries plot (the mountains would be horizontal, but I think it might be clearer for people).

**Comment by naught101** [comment]
timeseries can also be displayed vertically..

**Comment by rensa** [comment]
It could be interesting to present the distribution on the margin of the time series plot so as to emphasise that they're drawing from the same data. I do worry that it might be a little hard to digest as one bigger plot, though

**Comment by matlipson** [comment]
I like that idea, I think we should try it.
Although there was also talk about increasing the window for the distribution plot, which would complicate things again.

**Comment by naught101** [comment]
Might be cool to have an overlaid version of the distribution for all max temperatures (all year round), as well as the 15 days either side.

**Comment by rensa** [comment]
Yeah, we really need to sit down together and figure out what we wanna settle on for our extreme heat definition. That, in turn, probably means working out what we want from this thing (do we still want to pitch it to some news services)?
